#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"
INPUT_SOURCE_EVENT="AppleSelectedInputSourcesChangedNotification"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker
#

sketchybar --bar \
    position=top \
    y_offset=-1\
    height=34 \
    color="$TRANSPARENT" \
    blur_radius=30 \
    padding_left=10


##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default \
    padding_left=0 \
    padding_right=0 \
    icon.font="JetBrainsMono Nerd Font:Bold:19.0" \
    label.font="SF Mono:SemiBold:14.0" \
    icon.color=$WHITE \
    label.color=$WHITE \
    icon.padding_left=4 \
    icon.padding_right=4 \
    label.padding_left=4 \
    label.padding_right=4


##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item apple left \
    --set apple \
        y_offset=-1 \
        label.drawing=off \
        icon.padding_left=8 \
        icon.padding_right=10 \
        icon.y_offset=1 \
        background.color="$T_DARK_GRAY" \
        background.corner_radius=50 \
        background.border_width=3 \
        background.height=32 \
        background.padding_right=15 \
        script="$PLUGIN_DIR/apple.sh" 

sketchybar --add event aerospace_workspace_change
for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space."$sid" left \
        --subscribe space."$sid" aerospace_workspace_change \
        --set space."$sid" \
            width=34 \
            align=center \
            icon.drawing=off \
            background.color="$T_DARK_GRAY" \
            background.height=32 \
            label="$sid" \
            label.font.style="Heavy" \
            click_script="aerospace workspace $sid" \
            script="$PLUGIN_DIR/aerospace.sh $sid"
done
# Fix '1' being a bit off
sketchybar --set space.1 \
    label.padding_left=3


# Other symbol: 
sketchybar --add item chevron left \
           --set chevron \
                icon= \
                icon.font.size=12.0 \
                icon.padding_left=10 \
                label.drawing=off \


sketchybar --add item front_app left \
           --set front_app \
                icon.drawing=off \
                label.width=200 \
                label.font="SF Pro:Bold:14.0" \
                background.padding_left=-17 \
                script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched
# For SF Mono: background.padding_left=-32


##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
    --set clock \
        icon.drawing=off \
        label.padding_left=5 \
        label.padding_right=10 \
        label.font.style="Bold" \
        label.font.size=15.0 \
        label.y_offset=1 \
        background.color=$T_DARK_GRAY \
        update_freq=10 \
        script="$PLUGIN_DIR/clock.sh"
        # TODO: try making items rounded and with border
        # background.corner_radius=20 \
        # background.border_width=2 \
        # background.border_color="$BLACK_50$" \
        # background.height=30 \
        # background.y_offset=-2 \

sketchybar --add item date right \
    --set date \
        icon.drawing=off \
        label.padding_left=10 \
        label.padding_right=5 \
        label.font="SF Pro:Medium:14.0" \
        background.color=$T_DARK_GRAY \
        update_freq=60 \
        script="$PLUGIN_DIR/date.sh"

# sketchybar --add item sep1 right \
#     --set sep1 \
#         label="│" \
#         label.font="JetBrainsMono Nerd Font:Bold:14.0" \
#         label.color=$BLACK_85 \
#         label.drawing=off \
#         icon.drawing=off

sketchybar --add item battery right \
    --set battery \
        label.padding_right=10 \
        icon.padding_left=10 \
        background.color=$T_PURPLE \
        update_freq=120 \
        script="$PLUGIN_DIR/battery.sh" \
   --subscribe battery system_woke power_source_change


# sketchybar --add item sep2 right \
#     --set sep2 \
#         label="│" \
#         label.font="JetBrainsMono Nerd Font:Bold:14.0" \
#         label.color=$BLACK_85 \
#         label.drawing=off \
#         icon.drawing=off

# sketchybar --add item cpu right \
#     --set cpu \
#         update_freq=1 \
#         script="$PLUGIN_DIR/cpu.sh"

sketchybar --add item wifi right \
    --set wifi \
        icon.font="JetBrainsMono Nerd Font:Bold:17.0" \
        icon.padding_left=10 \
        icon.padding_right=1 \
        icon.y_offset=2 \
        label.padding_right=12 \
        label.font="SF Pro:SemiBold:11.0" \
        background.color=$T_BLUE \
        update_freq=15 \
        script="$PLUGIN_DIR/wifi.sh" \
    --subscribe wifi wifi_change

# sketchybar --add item sep3 right \
#     --set sep3 \
#         label="│" \
#         label.font="JetBrainsMono Nerd Font:Bold:14.0" \
#         label.color=$BLACK_85 \
#         label.drawing=off \
#         icon.drawing=off

sketchybar --add event input_change $INPUT_SOURCE_EVENT \
    --add item input_source right \
    --set input_source \
        icon.drawing=off \
        label.font.style="Heavy" \
        label.font.size=16.0 \
        label.align=center \
        label.padding_left=10 \
        label.padding_right=10 \
        background.color=$T_AQUA \
        script="$PLUGIN_DIR/input_source.sh" \
    --subscribe input_source input_change 

# sketchybar --add item sep4 right \
#     --set sep4 \
#         label="│" \
#         label.font="JetBrainsMono Nerd Font:Bold:14.0" \
#         label.color=$BLACK_85 \
#         label.drawing=off \
#         icon.drawing=off

sketchybar --add bracket rightbar apple clock battery wifi input_source \
    --set rightbar \
        background.drawing=on \
        background.height=34

# -> Tring to listen to input source change event
# sketchybar --add event input_change "AppleEnabledInputSourcesChangedNotification" \
#     --add item input_source right \
#     --set input_source \
#         script="$PLUGIN_DIR/input_source.sh" \
#     --subscribe input_source input_change

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify right \
    --set spotify \
        icon= \
        icon.y_offset=-1 \
        icon.padding_right=10 \
        icon.font.size=22.5 \
        label.drawing=off \
        script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked


##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
